version: "3.8"

services:
    database:
        container_name: database
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - "1433:1433"
        environment:
          SA_PASSWORD: "1q2w#E$R%T"
          ACCEPT_EULA: "Y"
    frontend:
        container_name: frontend
        entrypoint:
          - "sh"
          - "-c"
          - "chown -R root . && npm ci && npm run start"
        environment:
          NODE_ENV: development
          REACT_APP_API_URL: http://localhost:3001
        hostname: frontend
        image: registry.access.redhat.com/ubi8/nodejs-18-minimal@sha256:74af9dc2b620022c77fcd712b811f64a03c1444ff1e9b9596a242b2edf3cf96f
        links:
          - backend
        ports:
          - "3000:3000"
        volumes:
          - ./frontend:/app:z
          - /app/node_modules
        user: root
        working_dir: "/app"
    backend:
        container_name: backend
        # entrypoint:
        #   - "sh"
        #   - "-c"
        #   - "npm i && npm run start"
        hostname: backend
        image: backend
        build:
            dockerfile: webapi\Dockerfile
        # image: registry.access.redhat.com/ubi8/nodejs-18-minimal@sha256:74af9dc2b620022c77fcd712b811f64a03c1444ff1e9b9596a242b2edf3cf96f
        links:
          - database
        ports:
          - "3001:8080"
        # volumes:
        #   - ./backend:/app:z
        #   - /app/node_modules
        # user: root
        # working_dir: "/app"
        # depends_on:
        #   database:
        #     condition: service_healthy